version: "3"
services:
  # Messaging service
  rabbitmq_smartrank:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq_smartrank'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_smartrank_go_net

networks:
  rabbitmq_smartrank_go_net:
    driver: bridge